### ISSUE TITLE
Is it possible to use this with a SPA (single page application)?

### ISSUE THREAD

**Issue by frederikhors** [rivo/users#11]
Is it possible to use this with a SPA (single page application)?

Can we call those methods without HTML rendering?

**Comment by rivo** [comment]
I suppose you could strip out some of the functionality of the package so it can be used in an SPA. But it's not built for that so it would require you to dig into the code to see what you can reuse.

For example, a password reset requires that a link is sent to the user where they can reset their password. How would that work in your SPA? Other functions like [`SignUp()`](https://pkg.go.dev/github.com/rivo/users?utm_source=godoc#SignUp) perform a redirect when the user is already logged in. Would you want this to happen in your SPA as well? There's more that would need to be figured out. These are just two examples.

I'm not saying it's impossible. But it would require rewriting parts of this package.

As a side note, in my software where I use this package, all the user handling (i.e. this package's functionality) is done with individual pages and the main functionality of the software is an SPA on a separate URL, mostly because it requires a lot of client-based functionality written in Javascript.

**Comment by frederikhors** [comment]
> As a side note, in my software where I use this package, all the user handling (i.e. this package's functionality) is done with individual pages and the main functionality of the software is an SPA on a separate URL, mostly because it requires a lot of client-based functionality written in Javascript.

Yeah. I'm thinking about it too, but I don't really like the idea.

Thanks for your wonderful work. I will decide what to do shortly.
