### ISSUE TITLE
Mobile clients

### ISSUE THREAD

**Issue by maberer** [rivo/users#2]
If I need to create tokens for mobile clients (that do not require cookies), what is the preferred way to use this library?

**Comment by maberer** [comment]
I think it would be good, if a function could be provided, that handles session ID retrieve and set. That would enable us to retrieve a session that is provided in a Authorization Token header instead of a cookie...

**Comment by rivo** [comment]
I'm not sure what you mean by "mobile clients that do not require cookies". This library is built on `rivo/sessions` which relies on cookies for pretty much everything, even if it is a mobile/responsive website.

Maybe you can explain your use case a bit so I can find out if this package meets your requirements?

**Comment by maberer** [comment]
Sorry, that my question was not clear.  By mobile clients I meant Android or iOS applications that would request the endpoints of a RESTful API. I basically want to build authentication for a website using cookies (provided by this library) as well as authentication from a mobile application. While websites traditionally use cookies, apps for Android or iOS normally use tokens for authentication...

The library seems to focus on cookies, making it unsuitable for sending a token in the Authorization header...

So I am not sure, what you would recommend in that case. 

Thanks for your time.

**Comment by rivo** [comment]
Thanks for the explanation. The [`rivo/sessions`](https://github.com/rivo/sessions) package deals with cookies only so there's no other form of authorization. At the same time, I think the question is what exactly you would need access to via your RESTful API and how authorization is supposed to work. Will your mobile app also authenticate using email+password? Or will they get a token in a different way (e.g. via a Facebook/Google login)? Once authorized, what information does the token map to? A user ID? Will you want to exchange tokens periodically or revoke them if required? Or will you rather work with a JWT that you won't save in your database?

For reference, I can point you to the parts in the source code where the password is validated. The rest is rather a matter of your own workflow and database design. For cookie-based sessions, best practices have evolved in the last 20 years and it's quite clear now how to set them up. But for RESTful APIs, there is a whole range of authorization options to choose from. So I think, if you haven't already, you'll need to decide on one which suits your application.

**Comment by maberer** [comment]
The app should also authenticate via email+password.... the same way as the website does; but instead of a cookie, the auth token (session ID) is sent in the Auth header of the API call.
The token will map to a user ID. On the backend, there is a minimal difference between the 2 different clients (website, app) aside from the transport of the session ID.... (cookie vs header).
To keep it simple, I would prefer token revocation if required... that excludes JWTs, since they are not meant to be used for session IDs (revocation difficulties...).

So after all, I really think, that in this case, the only big difference between the website and an app would be the form of transport for the session identifier...

Your library is awesome and it is truly sad, that I cannot fully utilize it to cover both scenarios.
Not sure if/how I can use it, at least I hope, that I can get some best practices/ideas for my case.

I would be thankful, if you could spend some words/thoughts on how you would realize it....

**Comment by maberer** [comment]
OK I think I was pretty confused...
I guess that I can use this library for all website based stuff with cookie auth and for the mobile app, I will have special routes under the API subdomain anyway: https://api.... 

So I can basically create/consume my own token implementation on this API endpoints... completely separated from the website cookie auth... 

When the mobile app logs in via email/password, I can create the password hash, load the user by calling LoadUserByEmail() and get the hashed password with user.GetPasswordHash()... for comparison... After that, I can create a token and send it down to my mobile app...

So I think I can use your great library for the website and combine it with token generation for the mobile app... (handled/designed by my own requirements...)

I think that's the way to go.... please let me know about your thoughts...

**Comment by rivo** [comment]
I think you are completely right. The library helps with the cookie-/website-part. There are quite a few things to consider when you deal with cookie-based sessions, which is why I created it.

Authentication for APIs is a bit simpler and it depends a lot on your database model. Because it's a different use case, I didn't include it here. (And in the end, much of it would have been Go interfaces and not a lot of actual functionality.)

Off the top of my head, you can have a table (or key-value store) for tokens which could look something like this:

|Column|Type|
|-|-|
|user_id|string|
|token|string|
|created|datetime|
|last_access|datetime|

With an index on `user_id` and one on `token`. When the app authenticates, you can compare the user's password just like [here](https://github.com/rivo/users/blob/08b7cfc1b832564ac9f2b43f5684bdc2e77b80f2/loginout.go#L53):

```go
bcrypt.CompareHashAndPassword(user.GetPasswordHash(), []byte(password))
```

and either return an existing token from the table above (if you only accept one) or insert a new token and return that one. (If you're using [user states](https://github.com/rivo/users/blob/08b7cfc1b832564ac9f2b43f5684bdc2e77b80f2/user.go#L10), you'll want to check those, too.)

Looking up a provided token and determining the associated user ID should be trivial. And revoking a token simply means deleting an entry from the table.

Using `created` and `last_access`, you could also give your tokens a maximum lifetime / idle time.

Let me know if this helps you a bit.

**Comment by maberer** [comment]
Thank you so much - this is very helpful information.

I integrated the library and it works very well for website cookie auth.
App authentication will be integrated next week... I think this should be pretty painless with all the information.

I still have to decide reasonable lifetime/idle times for my tokens... since my content is not too critical, I think I can keep them pretty high...

I am not planning to periodically refresh the token itself or apply any fancy access/refresh token schemes like used in oauth2....  I hope, that the easier scheme outlined here is sufficient.
Do you have an opinion in favor/against one of the more complex schemes (refresh-tokens...) mentioned above...?

The more complex variants have their disadvantages too... I guess I will stick with one proposed.
